### PR TITLE
Updated to install WinAppDriver v0.7

### PR DESCRIPTION
**Pull request by yodurr**

### CODE REVIEW

**Comment by rkavalap** [comment]
@yodurr  I am not agains't this change. But this will not scale trying to make a commit for every release of winappdriver.

We should just add http request and parse the json response for the latest msi
https://api.github.com/repos/Microsoft/WinAppDriver/releases/latest

We should probably expose the version as a appium server side capability for end user to request, like how we do it for chromedriver today.

**Comment by jlipps** [comment]
@rkavalap I'm in favor of adding an npm install flag to override the version, as we do with chromedriver, but I'm not in favor of having the package download the latest msi. Appium installs need to be completely deterministic; right now at any rate, if you install a specific version of Appium, it needs to install a specific version of WinAppDriver. Otherwise chaos will ensue :-)

**Comment by jlipps** [comment]
published as 0.3.0. @yodurr i don't have my windows machine on me, can someone npm install this rev and run a basic test? if you want to do it through appium, simply doing `rm -rf node_modules && npm install` on appium HEAD should bring this rev of windows driver in.

**Comment by yodurr** [comment]
just tested e2e and it worked.  Appium now installs WinAppDriver v0.7 and successfully launches and proxies to it when running a test.

**Comment by jlipps** [comment]
Excellent, will begin the release process

**Pull request merged**
