### PR TITLE
WinAppDriver v1.1RC Install

### PR DESCRIPTION
**Pull request by hassanuz**
Updated Appium installer to install latest v1.1 RC of WinAppDriver. Please squash the two commits when accepting if possible. Thank you!

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Thanks @hassanuz 

Can you please accept the CLA?

**Comment by mykola-mokhnach** [comment]
@hassanuz the bot verifies the signature based on the email address of your local git account. Can you please make sure this address is properly set on the machine where the current PR was made?

**Comment by hassanuz** [comment]
Hi @mykola-mokhnach, 

I did sign the CLA using the same email address used by my GitHub account, and it was through this account where I pushed the PR. 

Perhaps I should resubmit a new PR?

**Comment by mykola-mokhnach** [comment]
You may to to make a new commit here after the email has been fixed. If that does not help then it would be the best to resubmit it, yes.

**Comment by hassanuz** [comment]
Hi @mykola-mokhnach, 

I've amended the previous commits with the right authoring info, so the signature process should now go through. 

Is it best if we continue with this PR, or remove it, and have me submit a new PR (I can't resubmit with this PR being active on the branch)?

Thanks,
Hassan

**Comment by mykola-mokhnach** [comment]
Thanks. I think all good now

**Pull request merged**
