### PR TITLE
Fix typo in py example

### PR DESCRIPTION
**Pull request by sarah-github**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Thanks for the update. This code example is generally outdated. Let me update the capabilities format

**Comment by sarah-github** [comment]
Thanks. Can the windows tests only be run on windows itself? My first thought was, to connect appium and appium windows driver installed on linux with the WinAppDriver server installation on a windows machine via network port, and execute the python tests on linux, but this currently leads to problems.

**Comment by mykola-mokhnach** [comment]
Appium server itself must be run on Windows host, however the client code could be executed from any host. It talks to the server using REST API, so it does not really matter what client OS is unless it can send HTTP requests.
Check https://github.com/appium/appium-windows-driver#usage

**Comment by mykola-mokhnach** [comment]
Closed as obsolete

**Pull request closed without merging**
